name = "L1DRAC"
uuid = "cfe1ccb9-c379-4044-ad53-5140b82cb9e3"
authors = ["Aditya Gahlawat"]
version = "1.0.0-DEV"

[deps]
ControlSystemsBase = "aaaaaaaa-a6ca-5380-bf3e-84a91bcd477e"
DifferentialEquations = "0c46a032-eb83-5123-abaf-570d42b7fbaa"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
InteractiveErrors = "6cff3a6f-7015-4b3b-b269-4b312a73b9bf"
LaTeXStrings = "b964fa9f-0449-5b57-a5c2-d3ea65f4040f"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
OrdinaryDiffEq = "1dea7af3-3e70-54e6-95c3-0bf5283fa5ed"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
PlutoUI = "7f904dfe-b85e-4ff6-b463-dae2292396a8"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
StatsPlots = "f3b207a7-027a-5e70-b257-86293d7955fd"
StochasticDiffEq = "789caeaf-c7a9-5a7d-9973-96adeb23e2a0"
UnPack = "3a884ed6-31ef-47d7-9d2a-63182c4928ed"

[compat]
ControlSystemsBase = "1.18.2"
DifferentialEquations = "7.16.1"
Distributions = "0.25.120"
InteractiveErrors = "1.0.1"
LaTeXStrings = "1.4.0"
LinearAlgebra = "1.11.0"
OrdinaryDiffEq = "6.101.0"
Plots = "1.40.19"
PlutoUI = "0.7.71"
Random = "1.11.0"
StatsPlots = "0.15.7"
StochasticDiffEq = "6.81.0"
UnPack = "1.0.2"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
