name = "L1DRAC"
uuid = "cfe1ccb9-c379-4044-ad53-5140b82cb9e3"
version = "1.0.0-DEV"
authors = ["Aditya Gahlawat"]

[deps]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
CUDA = "052768ef-5323-5732-b1bb-66c8b64840ba"
ControlSystemsBase = "aaaaaaaa-a6ca-5380-bf3e-84a91bcd477e"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
DiffEqGPU = "071ae1c0-96b5-11e9-1965-c90190d839ea"
DifferentialEquations = "0c46a032-eb83-5123-abaf-570d42b7fbaa"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
InteractiveErrors = "6cff3a6f-7015-4b3b-b269-4b312a73b9bf"
Ipopt = "b6b21f68-93f8-5de0-b562-5493be1d77c9"
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"
LaTeXStrings = "b964fa9f-0449-5b57-a5c2-d3ea65f4040f"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
OptimalTransport = "7e02d93a-ae51-4f58-b602-d97af76e3b33"
OrdinaryDiffEq = "1dea7af3-3e70-54e6-95c3-0bf5283fa5ed"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
PlutoUI = "7f904dfe-b85e-4ff6-b463-dae2292396a8"
ProgressLogging = "33c8b6b6-d38a-422a-b730-caa89a2f386c"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StatsPlots = "f3b207a7-027a-5e70-b257-86293d7955fd"
StochasticDiffEq = "789caeaf-c7a9-5a7d-9973-96adeb23e2a0"
TerminalLoggers = "5d786b92-1e48-4d6f-9151-6b4477ca9bed"
UnPack = "3a884ed6-31ef-47d7-9d2a-63182c4928ed"

[compat]
BenchmarkTools = "1.6.3"
CSV = "0.10.15"
CUDA = "5.9.5"
ControlSystemsBase = "1.18.2"
DataFrames = "1.8.1"
Dates = "1.11.0"
DiffEqGPU = "3.9.0"
DifferentialEquations = "7.16.1"
Distributions = "0.25.120"
InteractiveErrors = "1.0.1"
Ipopt = "1.13.0"
JuMP = "1.29.3"
LaTeXStrings = "1.4.0"
LinearAlgebra = "1.11.0"
Logging = "1.11.0"
OptimalTransport = "0.3.20"
OrdinaryDiffEq = "6.101.0"
Plots = "1.40.19"
PlutoUI = "0.7.71"
ProgressLogging = "0.1.5"
Random = "1.11.0"
Revise = "3.13.0"
StaticArrays = "1.9.16"
Statistics = "1.11.1"
StatsPlots = "0.15.7"
StochasticDiffEq = "6.81.0"
TerminalLoggers = "0.1.7"
UnPack = "1.0.2"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
