name = "L1DRAC"
uuid = "cfe1ccb9-c379-4044-ad53-5140b82cb9e3"
authors = ["Aditya Gahlawat"]
version = "1.0.0-DEV"

[deps]
DifferentialEquations = "0c46a032-eb83-5123-abaf-570d42b7fbaa"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
OrdinaryDiffEq = "1dea7af3-3e70-54e6-95c3-0bf5283fa5ed"

[compat]
DifferentialEquations = "7.16.1"
LinearAlgebra = "1.11.0"
OrdinaryDiffEq = "6.101.0"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
